# Generated by Django 4.0.5 on 2022-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_gst_percent_branch_percent_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number'),
        ),
    ]
