# Generated by Django 4.0.5 on 2022-06-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_branch_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='province',
            field=models.CharField(max_length=30, verbose_name='Province'),
        ),
    ]
