# Generated by Django 4.0.5 on 2022-06-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_branch_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('stock', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Stock')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('make', models.CharField(max_length=30, verbose_name='Make')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('trim', models.CharField(max_length=30, verbose_name='Trim')),
                ('mileage', models.IntegerField(verbose_name='Mileage')),
                ('mileage_units', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=2, verbose_name='Mileage Units')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='used', max_length=4, verbose_name='Type')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('body_style', models.CharField(blank=True, max_length=20, null=True, verbose_name='Body Style')),
                ('body_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Body Type')),
                ('engine_type', models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='gas', max_length=8, verbose_name='Engine Type')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.branch', verbose_name='Branch')),
            ],
        ),
    ]
