# Generated by Django 4.0.5 on 2022-06-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='disclosures',
            field=models.TextField(blank=True, null=True, verbose_name='Disclosures'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_location',
            field=models.TextField(blank=True, null=True, verbose_name='Pickup Location'),
        ),
    ]
