# Generated by Django 4.0.5 on 2022-06-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vehicle_disclosures_vehicle_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='disclosures',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Disclosures'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Pickup Location'),
        ),
    ]
