# Generated by Django 4.0.5 on 2022-06-25 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('inventory', '0004_vehicle_purchase_order_vehicle_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder', verbose_name='Sales Order'),
        ),
    ]
