# Generated by Django 4.0.5 on 2022-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Postal Code')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number')),
                ('notes', models.CharField(blank=True, max_length=254, null=True, verbose_name='Additional Information')),
            ],
        ),
    ]
