# Generated by Django 4.0.5 on 2022-06-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_alter_purchaseorder_method_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Charged')),
                ('date_requested', models.DateField(blank=True, default=None, null=True, verbose_name='Date Requested')),
                ('date_received', models.DateField(blank=True, default=None, null=True, verbose_name='Date Received')),
                ('scan', models.ImageField(blank=True, null=True, upload_to='registrations/', verbose_name='Registration')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder', verbose_name='Sales Order')),
            ],
        ),
    ]
