# Generated by Django 4.0.5 on 2022-06-22 04:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('sale_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Sale Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Price')),
                ('pst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='PST Charged')),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='GST Charged')),
                ('method', models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment Method')),
                ('notes', models.CharField(max_length=64, verbose_name='Payment Notes')),
                ('sale_mileage', models.IntegerField(default=0, verbose_name='Sale Mileage')),
                ('sale_date', models.DateField(default=datetime.date.today, verbose_name='Date Sold')),
                ('paid_date', models.DateField(blank=True, default=None, null=True, verbose_name='Date Paid')),
                ('bill_of_sale', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bill of Sale')),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='customers.customer', verbose_name='Purchaser')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Sales Person')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Purchase Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price')),
                ('pst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='PST Paid')),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='GST Paid')),
                ('method', models.CharField(max_length=64, verbose_name='Payment Method')),
                ('notes', models.CharField(max_length=64, verbose_name='Payment Notes')),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='Purchase Date')),
                ('asking_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Asking Price')),
                ('bill_of_sale', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bill of Sale')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Sales Person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.customer', verbose_name='Seller')),
            ],
        ),
    ]
