# Generated by Django 4.0.5 on 2022-06-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_vehicle_purchase_order_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vehicle',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle', verbose_name='Vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicle',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle', verbose_name='Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment Notes'),
        ),
    ]
