# Generated by Django 4.0.5 on 2022-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_purchaseorder_vehicle_salesorder_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='method',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment Notes'),
        ),
    ]
